export const CREATE_LAYER = "CREATE_LAYER";
export const UPDATE_LAYERS = "UPDATE_LAYERS";
export const SET_SELECTED_LAYER = "SET_SELECTED_LAYER";
export const ADD_LAYER_IMAGE = "ADD_LAYER_IMAGE";
export const REMOVE_LAYER_IMAGE = "ADD_LAYER_IMAGE";
export const UPDATE_RARITY = "UPDATE_RARITY";
export const DELETE_IMAGE = "DELETE_IMAGE";
